-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO
JOIN ANIMAL_INS AI
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'I%' AND (AO.SEX_UPON_OUTCOME LIKE 'S%' OR AO.SEX_UPON_OUTCOME LIKE 'N%')
ORDER BY AO.ANIMAL_ID;